routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Auth\PasswordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AssetsController;
use App\Http\Controllers\AllowUserLogsController;
use App\Http\Controllers\AssetsMasterController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\HolidaysController;
use App\Http\Controllers\HolidaysMasterController;
use App\Http\Controllers\HolidaysYearController;
use App\Http\Controllers\AptitudeController;
use App\Http\Controllers\LeavesController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\ServicesController;
use App\Http\Controllers\ShowController;
use App\Http\Controllers\TimeloggerController;
use App\Http\Controllers\UserPermissionController;
use App\Http\Controllers\userPermissionMaster;
use App\Http\Controllers\WeeklyLogsController;
use App\Http\Controllers\WorkingDaysController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/dashboard',[TimeloggerController::class,'admin'])->middleware(['auth'])->name('dashboard.admin');
Route::get('/logout',[AuthenticatedSessionController::class,'destroy'])->name('Logout');

Route::group(['middleware' => 'web'], function() {


    Route::post('/trash',[TimeloggerController::class, 'trash'])->name('user.trash');
    Route::get('/recyclebin',[TimeloggerController::class, 'recyclebin'])->name('user.recyclebin');

    Route::get('/restore/{id}',[TimeloggerController::class, 'restore'])->name('user.restore');

    Route::get('/user/delete/{id}',[TimeloggerController::class, 'destroy'])->name('user.destroy');

    Route::get('denied',function(){
            return 'denied';
        })->name('user.denied');
     

    /*User authinticate*/
    Route::group(array('middleware' => ['auth']), function(){

            // Route::get('dashboard',[TimeloggerController::class,'admin'])->name('dashboard.admin');

            Route::post('get-selected-pemission',[UserPermissionController::class,'getSelectedPermissions'])->name('selectpermission.get');
           
           
        //karishma  
            Route::post('leaves/delete',[LeavesController::class,'destroy'])->name('leaves.delete');
            Route::post('leave/status',[LeavesController::class,'leaveStatus'])->name('leave.status');

            Route::post('notification/isread',[LeavesController::class,'notificationIsread'])->name('notification.isread');

            Route::post('notification/isview',[LeavesController::class,'notificationIsview'])->name('notification.isview');

            Route::post('leave/checkbox_status',[LeavesController::class,'checkboxtatus'])->name('leave.checkboxtatus');

            Route::get('logs/exportlogs/{id}/{month}/{year}',[ShowController::class,'exportlogs'])->name('logs.exportlogs');

            Route::get('logs/alluserexportlogs/{id}/{month}/{year}',[ShowController::class,'allUserExportLogs'])->name('logs.alluserexportlogs');

            Route::get('workingdays',[WorkingDaysController::class,'index'])->name('admin.workingdays');

            // Route::post('workingdays',[WorkingDaysController::class,'workingdays'])->name('admin.workingdays');

            Route::post('store/workingdays',[WorkingDaysController::class,'storeworkingdays'])->name('admin.store.workingdays');

            Route::get('user/profile/upload-photo/{id?}',[TimeloggerController::class,'getUploadProfilePhoto'])->name('user.profile.upload.get');

            Route::post('user/profile/upload-photo',[TimeloggerController::class,'postUploadProfilePhoto'])->name('user.profile.upload.post');

            Route::get('/user/profile/crop-photo',[TimeloggerController::class,'getCropProfilePhoto'])->name('user.profile.photo.crop.get');

            Route::post('/user/profile/crop-photo',[TimeloggerController::class,'postCropProfilePhoto'])->name('user.profile.photo.crop.post');

            Route::post('/user/deactive',[TimeloggerController::class,'userDeactive'])->name('user.deactive');

            Route::post('position/store',[TimeloggerController::class,'positionStore'])->name('position.store');

            Route::post('/leaves/chart',[TimeloggerController::class,'getChart'])->name('dashboard.leaves.chart');

            Route::post('/leaves/secondchart',[TimeloggerController::class,'getSecondChart'])->name('dashboard.leaves.secondchart');

            Route::post('/leaves/logs-chart',[TimeloggerController::class,'getLogsChart'])->name('dashboard.logs.chart');

            Route::post('workingdays/hours',[TimeloggerController::class,'workingdaysHours'])->name('admin.workingdays.hours');


            Route::resource('services',ServicesController::class,['except'=>['delete','show']]);
        
            Route::post('services/delete',[ServicesController::class,'delete'])->name('services.delete');
            Route::post('category/store',[ServicesController::class,'categoryStore'])->name('category.store');
            Route::get('weeklylogs',[WeeklyLogsController::class,'weeklyLogs'])->name('admin.weeklylogs');
            //end karishma
            //rushik
            Route::resource('/holiday-master',HolidaysMasterController::class,['except'=>['delete','show']]);
             
            Route::post('/holiday-master/delete',[HolidaysMasterController::class,'delete'])->name('holiday-master.delete');

            Route::resource('/holiday-year',HolidaysYearController::class,['except'=>['delete','show']]);
        
            Route::post('/holiday-year/delete',[HolidaysYearController::class,'delete'])->name('holiday-year.delete');

            Route::get('holiday/upload-photo',[HolidaysMasterController::class,'getUploadProfilePhoto'])->name('holiday.upload.get');

            Route::post('holiday/upload-photo',[HolidaysMasterController::class,'postUploadProfilePhoto'])->name('holiday.upload.post');
        
            Route::get('/holiday/crop-photo',[HolidaysMasterController::class,'getCropProfilePhoto'])->name('holiday.photo.crop.get');
       
            Route::post('/holiday/crop-photo',[HolidaysMasterController::class,'postCropProfilePhoto'])->name('holiday.photo.crop.post');

            Route::post('/dashboard/leaves/store',[LeavesController::class,'leavestore'])->name('dashboard.leaves.store');

            Route::post('/dashboard/leaves/second/store',[LeavesController::class,'leavesecondstore'])->name('dashboard.leaves.second.store');

            Route::post('/dashboard/leaves/third/store',[LeavesController::class,'leavethirdstore'])->name('dashboard.leaves.third.store');

            Route::post('/user/checkin',[TimeloggerController::class,'checkIn'])->name('user.checkin');

            Route::resource('assets',AssetsController::class,['except'=>['delete','show']]);

            Route::post('assets/delete',[AssetsController::class,'delete'])->name('assets.delete');

            Route::resource('assets/master',AssetsMasterController::class,['except'=>['delete','show']]);

            Route::get('assets/master/create',[AssetsMasterController::class,'create'])->name('assets.master.create');

            Route::get('assets/master/index',[AssetsMasterController::class,'index'])->name('assets.master.index');

            Route::post('assets/master/store',[AssetsMasterController::class,'store'])->name('assets.master.store');

            Route::get('assets/master/edit/{id}',[AssetsMasterController::class,'edit'])->name('assets.master.edit');

            Route::post('assets/master/delete',[AssetsMasterController::class,'delete'])->name('assets.master.delete'); 

            Route::post('assets/master/update',[AssetsMasterController::class,'update'])->name('assets.master.update');  
 

            Route::post('getDevice',[AssetsController::class,'getDevice'])->name('getDevice.index');  
            //end rushik

            Route::post('getlogs',[LogController::class,'getLogs'])->name('getlogs.index');  

            Route::post('logs/import/daily',[LogController::class,'importlogs'])->name('logs.logsimport');  
            Route::get('user/leaves/export/{user}/{type}/{year}',[LeavesController::class,'exportLeaves'])->name('leaves.export');  



        Route::group(array('middleware'=> ['acl']),function(){

                Route::resource('/user',TimeloggerController::class,['except'=>['destroy']]);
                Route::resource('/holiday',HolidaysController::class,['except'=>['destroy']]);
                Route::resource('/leaves',LeavesController::class,['except'=>['destroy','show']]);
                Route::resource('/allowuserlogs',AllowUserLogsController::class,['except'=>['destroy','show']]);


                Route::get('holiday/delete/{id}',[HolidaysController::class,'destroy'])->name('holidays.delete');  

                Route::get('leaves/{user_id}/create',[LeavesController::class,'userCreate'])->name('user.leaves.create');  

                Route::post('leaves/{user_id}/store',[LeavesController::class,'userStore'])->name('user.leaves.store');  

                Route::get('quiz-delete/{quiz_id}',[QuizController::class,'delete'])->name('quiz.delete');  
                Route::get('quiz-send/{quiz_id}',[QuizController::class,'send'])->name('quiz.send');  

                Route::resource('quiz',QuizController::class,['except'=>['destroy','show']]);
                
                Route::get('logs',[LogController::class,'index'])->name('logs.index');  

resources/views/dashboard/adminbk.blade.php
@extends('layout.layout')
@section('content')
@stop
<div class="content-wrapper">
        <div class="page-title">
            <div>
                <h1><i class="fa fa-dashboard"></i> Dashboard</h1>
            </div>
            
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-calendar-check-o fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                
                                <div><b>LOGS</b></div>
                                <!-- @if($logs['check_in'] == NULL AND $logs['check_in'] == '')
                                    Not Available
                                @else -->
                                    Date : <?= $logs['time'] ?>
                                    </br>
                                    @if($logs['check_in'])
                                    Check In : <?= $logs['check_in']; ?>
                                    @endif
                                    </br>
                                    @if($logs['check_out'])
                                    Check Out : <?= $logs['check_out'];?>
                                    @endif
                                <!-- @endif -->
                            </div>
                        </div>
                    </div>
                    <a href="<?= URL::route('logs.index') ?>">
                        <div class="panel-footer">
                            <span class="pull-left">View Details</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-green">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                            <i class="fa fa-plane fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                
                                <div><b>HOLIDAYS</b></div>
                                @if(!empty($holiday))
                                    {{ $holiday->holiday }}
                                @endif
                            </div>
                        </div>
                    </div>
                    <a href="<?= URL::route('holiday.index') ?>">
                        <div class="panel-footer">
                            <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
         <!--    <div class="col-lg-3 col-md-6">
                <div class="panel panel-yellow">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-user fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        
                                        <div><b>USER</b></div>
                                    </div>
                                </div>
                            </div>
                            <a href="<?= URL::route('show.user') ?>">
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
            </div> -->
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-calendar-minus-o fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                
                                <div><b>LEAVES</b></div>
                                @if($leaves['date'] == NULL AND $leaves['date'] == '')
                                    No leave Taken
                                @else
                                Leave Date : <?= $leaves->date; ?>
                                </br>       
                                Leave Purpose : <?= substr($leaves['leave_purpose'],0,20); ?>...
                                @endif
                            </div>
                        </div>
                    </div>
                    <a href="<?= URL::route('leaves.index') ?>">
                        <div class="panel-footer">
                            <span class="pull-left">View Details</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></semptypan>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="card">
          <h3 class="card-title">Bar Chart</h3>
          <div id="chartContainer" style="height: 345px; width: 100%;">
          </div>
          <!-- <div class="embed-responsive embed-responsive-16by9">
            <canvas class="embed-responsive-item" id="barChartDemo"></canvas>
          </div> -->
        </div>
</div>empty
@section('script')
<?= Html::script('asset/js/canvasjs.min.js') ?>

<script type="text/javascript">
    $(document).ready(function(){
        window.onload = function () {
            var chart = new CanvasJS.Chart("chartContainer",
            {
              theme: "theme2",
              axisX: {
                title: "Month"
              },
              width: 800,
              height:350,
              axisY: [
               {
                 title: "1st Primary Y Axis",
                 lineColor: "#4F81BC",
                 tickColor: "#4F81BC",
                 labelFontColor: "#4F81BC",
                 titleFontColor: "#4F81BC",
                 lineThickness: 2,
                 interval: 2,
                 maximum: 30,
              },
              // {
              //    title: "2nd Primary Y Axis",
              //    lineColor: "#C0504E",
              //    tickColor: "#C0504E",
              //    labelFontColor: "#C0504E",
              //    titleFontColor: "#C0504E",
              //    lineThickness: 2
              // }
            ],
              
            data: [
              {
                type: "column",             
                dataPoints: [
                  { x: 1, y: 14,label: "Jan" },
                  { x: 2, y: 2 ,label: "Feb"},
                  { x: 3, y: 5 ,label: "Mar"},
                  { x: 4, y: 7 ,label: "Apr"},
                  { x: 5, y: 1 ,label: "May"},
                  { x: 6, y: 5 ,label: "Jun"},
                ]
             },
             // {
             //   type: "column",
             //   axisYIndex: 1,
             //   dataPoints: [      
             //     { x: 1, y: 70 },
             //     { x: 2, y: 45 },
             //     { x: 3, y: 56 },
             //     { x: 4, y: 77 },
             //     { x: 5, y: 58 },
             //     { x: 6, y: 72 },
             //     { x: 7, y: 58 },
             //     { x: 8, y: 26 },
             //     { x: 9, y: 18 }
             //   ]
             // }
            ]
            });

            chart.render();
          }
        
    });
</script>
@stop

resources/views/dashboard/leave_form.blade.php
@foreach($date_of_leave as $key => $form)
<div class="parentdate" >
  <div class="childdate">
    {{csrf_field()}}
    <a href="#" class="clicktohide">
    <div class="lable_div">
      
    <h3 class="modal-heading modaldate"><span class="fa fa-plus"></span>{{ $form}}  {{ date('l',strtotime($form))}}</h3>
    </div>
    </a>
    <div class="inner_div">
    <input type="hidden" value="{{$form}}" class="date_field" name="hidden_field">

    <div class="form-group">
      <div class="animated-checkbox col-md-12">
        <label>
          <input type="radio" id="fulldaycheckbox" name="leave_detail[{{$form}}][day_type]" value="fullday" class="fulldaycheckboxclass" checked ><span class="label-text">Full day</span>
        </label>
        @if(date('l',strtotime($form)) == 'Sunday')
        @elseif(date('l',strtotime($form)) == 'Saturday' && (ceil(date('d',strtotime($form))/7) == 2 || ceil(date('d',strtotime($form))/7) == 4))
        @elseif(in_array(date("d-m-Y", strtotime($form)),$holiday_array))
        @else 
        <label>
          <input type="radio" id="halfdaycheckbox" name="leave_detail[{{$form}}][day_type]" value="halfday" class="halfdaycheckboxclass"  ><span class="label-text">Half day</span>
        </label>
        @endif
      </div>
    </div>
    <div class="form-group form_hour" id="hour" style="display: none;">
        <label class="control-label col-lg-3" for="leaveselecttype">Select Time:</label>
     
      <div class="col-md-9">
            <div class="input-group col-md-9 bootstrap-timepicker timepicker">
              <label>FirstHalf</label>
              <input type="radio" class="first_half" name="leave_detail[{{$form}}][half]" value="first_half">
              <label>SecondHalf</label>
              <input type="radio" class="second_half" name="leave_detail[{{$form}}][half]" value="second_half">
              <label>Custom Time</label>
              <input type="radio" name="leave_detail[{{$form}}][half]" value="custom_time" class="custom_time">
            </div> 
            <div class="input-group col-md-6 bootstrap-timepicker timepicker for_hide_show" style="display:none;">
              <div style="display: flex;">
                <input class="form-control timepicker2" placeholder="To hour" name="leave_detail[{{$form}}][from_hour]" type="text" value="10:00 AM">
                <input class="form-control timepicker1"  placeholder="From hour" name="leave_detail[{{$form}}][to_hour]"  type="text" value="07:00 PM">
              </div>
            </div> 
                <span class="time_error" style="color:red"></span>
      </div>
     
      <p class="help-block" style="color:red" id="error_hours"></p>
    </div>
    <div class="form-group">
      <label class="col-lg-3 control-label" for="leaveselecttype">Select Leave type</label>
    
      <div class="col-lg-9">
          @if($get_leavetype == 'Sick Leave')
          
            <input type="text" class="form-control second_step_leave_type s_leave" name="leave_detail[{{$form}}][leave_type]" value="Sick Leave" onkeydown="return false"/>
          @else
        <select class="form-control second_step_leave_type" name="leave_detail[{{$form}}][leave_type]" id="field_leave_detail" data-date="{{ $form }}">

          <option value="Casual Leave" id="c_leave" class="c_leave" @if($get_leavetype == 'Casual Leave') selected="selected" @endif >Casual Leave</option>
          <option value="Sick Leave" class="s_leave" @if($get_leavetype == 'Sick Leave') selected="selected" @endif >Sick/Emergency Leave</option>
          <option value="Privilege Leave" class="p_leave" @if($get_leavetype == 'Privilege Leave') selected="selected" @endif>Privilege Leave</option>
          
          @endif
        </select>
        <p class="help-block" style="color:red" id="error_leave_detail{{$form}}"></p>
      </div>
    </div>
    <div class="form-group">
      <label class="col-lg-3 control-label" for="leave-purpose">Leave-purpose</label>
      <div class="col-lg-9">
        <textarea class="form-control leave_pupose_form2" name="leave_detail[{{$form}}][leave_purpose]" type="text" placeholder="leave-purpose" rows="4">{{$get_leavepurpose}}</textarea>
        <p class="help-block" style="color:red" id="error_s_leavepurpose"></p>
      </div>
    </div>
    </div>
    </div>
</div>     
@endforeach
<!-- leaves status -->
<script>
  var sick_leaves = sick_leaves;
  var casual_leaves = casual_leaves;
  var priviledge_leaves = priviledge_leaves;
  var selected_date = [];
  var second_step = $('.second_step_leave_type');
  var date_field = $('.date_field');
  
  $(document).ready(function(){
    $(".firststatus").show();
  })
  d = new Date();
  d.setDate(d.getDate()+5);
  var date = convert(d);
  function convert(str) {
      var date = new Date(str),
      mnth = ("0" + (date.getMonth() + 1)).slice(-2),
      day = ("0" + date.getDate()).slice(-2);
      return [date.getFullYear(),mnth,day].join("-");
  }

  $.each(date_field,function(k,v){
    var dateField = $(v).val();
    selected_date[k] = dateField;
  });

  var leaves_date = {};
  $.each(selected_date,function(i,value){
     var leave_type = $('.second_step_leave_type').val();
     leaves_date[value] =leave_type;
  });

// date disabled code start from here

  // var disable = $(".second_step_leave_type").val();
  // alert(disable);
  // if (disable == "Sick Leave") {
  //   $('.p_leave').attr('disabled','disabled');
  //   $('.c_leave').attr('disabled','disabled');
  //   var new_date1 = [];
  //   var date_field1 = $('.date_field');
  //       $.each(date_field1,function(k,v){
  //         var newdateField1 = $(v).val();
  //         new_date1[k] = newdateField1;
  //       });
  //       var dates1 = {};
  //       for(var i = 0; i < new_date1.length; i++){
  //           dates1[new_date1[i]] = disable;
  //       }
  //       selectDate(dates1);
  // }else{
    $(".second_step_leave_type").on("change",function(){
        // $(".firstatus").show();
        var new_date = [];
        var new_leave = [];
        var leaves_type1 = $('.second_step_leave_type').val();
        var element = $(this).attr("data-date");
        var second_step = $('.second_step_leave_type');
        $.each(second_step,function(k,v){
           var new_leaves_type = $(v).val();
           new_leave[k] = new_leaves_type;
        });

        var date_field = $('.date_field');
        $.each(date_field,function(k,v){
          var newdateField = $(v).val();
          new_date[k] = newdateField;
        });
        var dates = {};
        for(var i = 0; i < new_date.length; i++){
            dates[new_date[i]] = new_leave[i];
        }
        selectDate(dates)
    });
  // }
  function selectDate(dates)
  {
    $(".firststatus").empty();
    $(".firststatus").show();
    var casualleves = 0;
    var priviledgeleaves = 0;
    var sickleaves = 0;
    var seleted_date_arr = {};
    var arr_count = Object.entries(dates);
    var casualpaid = 0;
    var priviledgepaid = 0;
    var sickpaid = 0;

    $.each(dates,function(value,key){
    var value = value.split("-").reverse().join("-");
    if(key == "Casual Leave")
    {
        casualleves++;
        var casual_available = 6 - casual_leaves;
        if(casualleves > casual_available)
        {
            if(value > date)
            {
              if(casualpaid < casual_available)
              {
                 seleted_date_arr[value] = "Paid";
                 casualpaid++;
              }else{
                seleted_date_arr[value] = "UnPaid";
              }
            }else{
                 seleted_date_arr[value] = "UnPaid";
            }
        
        }else{
            if(value > date)
            {
               if(casualpaid < casual_available){
                   seleted_date_arr[value] = "Paid";
                   casualpaid++;
                }else{
                  seleted_date_arr[value] = "UnPaid";
                }
            }else{
                seleted_date_arr[value] = "UnPaid";
            }
        }
      }else if(key == "Privilege Leave")
      {
        priviledgeleaves++;

        var priviledge_available = 6 - priviledge_leaves;
        
        if(priviledgeleaves > priviledge_available)
        {
            if(value > date)
            {
              if(priviledgepaid < priviledge_available)
              {
                 seleted_date_arr[value] = "Paid";
                 priviledgepaid++;
              }else{
                seleted_date_arr[value] = "UnPaid";
              }
            }else{
                 seleted_date_arr[value] = "UnPaid";
            }
        }else{
            if(value > date)
            {
               if(priviledgepaid < priviledge_available)
               {
                   seleted_date_arr[value] = "Paid";
                   priviledgepaid++;
                }else{
                  seleted_date_arr[value] = "UnPaid";
                }
            }else{
                seleted_date_arr[value] = "UnPaid";
            }
        }
      }else if(key == "Sick Leave")
      {
        sickleaves++;
        var sick_available = 6 - sick_leaves;

        if(sickleaves > sick_available)
        {
            if(sickpaid < sick_available)
            {
               seleted_date_arr[value] = "Paid";
               sickpaid++;
            }else{
              seleted_date_arr[value] = "UnPaid";
            }
        }else{
           if(sickpaid < sick_available){
               seleted_date_arr[value] = "Paid";
               sickpaid++;
            }else{
              seleted_date_arr[value] = "UnPaid";
            }
        } 
       }
    });
    $.each(seleted_date_arr,function(i,value){
       var i = i.split("-").reverse().join("-");
       $('.firststatus').append(" "+i+" : "+value+" , ");
    });
  }
$(".clicktohide").next(".inner_div").removeClass("active").slideUp()
$(".clicktohide").click(function(){
      if($(this).next(".inner_div").hasClass("active")){
        $(this).next(".inner_div").removeClass("active").slideUp()
        $(this).children("span").removeClass("fa-minus").addClass("fa-plus")
      }
      else{
        // $(" .inner_div").removeClass("active").slideUp()
        $(".clicktohide span").removeClass("fa-minus").addClass("fa-plus");
        $(this).next(".inner_div").addClass("active").slideDown()
        $(this).children("span").removeClass("fa-plus").addClass("fa-minus")
      }
      });
</script>
<!-- end leaves status -->
<style>
  .form_hour .control-label{
    padding-top: 0;
  }
  .form_hour input, .animated-checkbox input{
    margin: 0 7px;
  }
</style>