routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Auth\PasswordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AssetsController;
use App\Http\Controllers\AllowUserLogsController;
use App\Http\Controllers\AssetsMasterController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\HolidaysController;
use App\Http\Controllers\HolidaysMasterController;
use App\Http\Controllers\HolidaysYearController;
use App\Http\Controllers\AptitudeController;
use App\Http\Controllers\LeavesController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\ServicesController;
use App\Http\Controllers\ShowController;
use App\Http\Controllers\TimeloggerController;
use App\Http\Controllers\UserPermissionController;
use App\Http\Controllers\userPermissionMaster;
use App\Http\Controllers\WeeklyLogsController;
use App\Http\Controllers\WorkingDaysController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/dashboard',[TimeloggerController::class,'admin'])->middleware(['auth'])->name('dashboard.admin');
Route::get('/logout',[AuthenticatedSessionController::class,'destroy'])->name('Logout');

Route::group(['middleware' => 'web'], function() {


    Route::post('/trash',[TimeloggerController::class, 'trash'])->name('user.trash');
    Route::get('/recyclebin',[TimeloggerController::class, 'recyclebin'])->name('user.recyclebin');

    Route::get('/restore/{id}',[TimeloggerController::class, 'restore'])->name('user.restore');

    Route::get('/user/delete/{id}',[TimeloggerController::class, 'destroy'])->name('user.destroy');

    Route::get('denied',function(){
            return 'denied';
        })->name('user.denied');
     

    /*User authinticate*/
    Route::group(array('middleware' => ['auth']), function(){

            // Route::get('dashboard',[TimeloggerController::class,'admin'])->name('dashboard.admin');

            Route::post('get-selected-pemission',[UserPermissionController::class,'getSelectedPermissions'])->name('selectpermission.get');
           
           
        //karishma  
            Route::post('leaves/delete',[LeavesController::class,'destroy'])->name('leaves.delete');
            Route::post('leave/status',[LeavesController::class,'leaveStatus'])->name('leave.status');

            Route::post('notification/isread',[LeavesController::class,'notificationIsread'])->name('notification.isread');

            Route::post('notification/isview',[LeavesController::class,'notificationIsview'])->name('notification.isview');

            Route::post('leave/checkbox_status',[LeavesController::class,'checkboxtatus'])->name('leave.checkboxtatus');

            Route::get('logs/exportlogs/{id}/{month}/{year}',[ShowController::class,'exportlogs'])->name('logs.exportlogs');

            Route::get('logs/alluserexportlogs/{id}/{month}/{year}',[ShowController::class,'allUserExportLogs'])->name('logs.alluserexportlogs');

            Route::get('workingdays',[WorkingDaysController::class,'index'])->name('admin.workingdays');

            // Route::post('workingdays',[WorkingDaysController::class,'workingdays'])->name('admin.workingdays');

            Route::post('store/workingdays',[WorkingDaysController::class,'storeworkingdays'])->name('admin.store.workingdays');

            Route::get('user/profile/upload-photo/{id?}',[TimeloggerController::class,'getUploadProfilePhoto'])->name('user.profile.upload.get');

            Route::post('user/profile/upload-photo',[TimeloggerController::class,'postUploadProfilePhoto'])->name('user.profile.upload.post');

            Route::get('/user/profile/crop-photo',[TimeloggerController::class,'getCropProfilePhoto'])->name('user.profile.photo.crop.get');

            Route::post('/user/profile/crop-photo',[TimeloggerController::class,'postCropProfilePhoto'])->name('user.profile.photo.crop.post');

            Route::post('/user/deactive',[TimeloggerController::class,'userDeactive'])->name('user.deactive');

            Route::post('position/store',[TimeloggerController::class,'positionStore'])->name('position.store');

            Route::post('/leaves/chart',[TimeloggerController::class,'getChart'])->name('dashboard.leaves.chart');

            Route::post('/leaves/secondchart',[TimeloggerController::class,'getSecondChart'])->name('dashboard.leaves.secondchart');

            Route::post('/leaves/logs-chart',[TimeloggerController::class,'getLogsChart'])->name('dashboard.logs.chart');

            Route::post('workingdays/hours',[TimeloggerController::class,'workingdaysHours'])->name('admin.workingdays.hours');


            Route::resource('services',ServicesController::class,['except'=>['delete','show']]);
        
            Route::post('services/delete',[ServicesController::class,'delete'])->name('services.delete');
            Route::post('category/store',[ServicesController::class,'categoryStore'])->name('category.store');
            Route::get('weeklylogs',[WeeklyLogsController::class,'weeklyLogs'])->name('admin.weeklylogs');
            //end karishma
            //rushik
            Route::resource('/holiday-master',HolidaysMasterController::class,['except'=>['delete','show']]);
             
            Route::post('/holiday-master/delete',[HolidaysMasterController::class,'delete'])->name('holiday-master.delete');

            Route::resource('/holiday-year',HolidaysYearController::class,['except'=>['delete','show']]);
        
            Route::post('/holiday-year/delete',[HolidaysYearController::class,'delete'])->name('holiday-year.delete');

            Route::get('holiday/upload-photo',[HolidaysMasterController::class,'getUploadProfilePhoto'])->name('holiday.upload.get');

            Route::post('holiday/upload-photo',[HolidaysMasterController::class,'postUploadProfilePhoto'])->name('holiday.upload.post');
        
            Route::get('/holiday/crop-photo',[HolidaysMasterController::class,'getCropProfilePhoto'])->name('holiday.photo.crop.get');
       
            Route::post('/holiday/crop-photo',[HolidaysMasterController::class,'postCropProfilePhoto'])->name('holiday.photo.crop.post');

            Route::post('/dashboard/leaves/store',[LeavesController::class,'leavestore'])->name('dashboard.leaves.store');

            Route::post('/dashboard/leaves/second/store',[LeavesController::class,'leavesecondstore'])->name('dashboard.leaves.second.store');

            Route::post('/dashboard/leaves/third/store',[LeavesController::class,'leavethirdstore'])->name('dashboard.leaves.third.store');

            Route::post('/user/checkin',[TimeloggerController::class,'checkIn'])->name('user.checkin');

            Route::resource('assets',AssetsController::class,['except'=>['delete','show']]);

            Route::post('assets/delete',[AssetsController::class,'delete'])->name('assets.delete');

            Route::resource('assets/master',AssetsMasterController::class,['except'=>['delete','show']]);

            Route::get('assets/master/create',[AssetsMasterController::class,'create'])->name('assets.master.create');

            Route::get('assets/master/index',[AssetsMasterController::class,'index'])->name('assets.master.index');

            Route::post('assets/master/store',[AssetsMasterController::class,'store'])->name('assets.master.store');

            Route::get('assets/master/edit/{id}',[AssetsMasterController::class,'edit'])->name('assets.master.edit');

            Route::post('assets/master/delete',[AssetsMasterController::class,'delete'])->name('assets.master.delete'); 

            Route::post('assets/master/update',[AssetsMasterController::class,'update'])->name('assets.master.update');  
 

            Route::post('getDevice',[AssetsController::class,'getDevice'])->name('getDevice.index');  
            //end rushik

            Route::post('getlogs',[LogController::class,'getLogs'])->name('getlogs.index');  

            Route::post('logs/import/daily',[LogController::class,'importlogs'])->name('logs.logsimport');  
            Route::get('user/leaves/export/{user}/{type}/{year}',[LeavesController::class,'exportLeaves'])->name('leaves.export');  



        Route::group(array('middleware'=> ['acl']),function(){

                Route::resource('/user',TimeloggerController::class,['except'=>['destroy']]);
                Route::resource('/holiday',HolidaysController::class,['except'=>['destroy']]);
                Route::resource('/leaves',LeavesController::class,['except'=>['destroy','show']]);
                Route::resource('/allowuserlogs',AllowUserLogsController::class,['except'=>['destroy','show']]);


                Route::get('holiday/delete/{id}',[HolidaysController::class,'destroy'])->name('holidays.delete');  

                Route::get('leaves/{user_id}/create',[LeavesController::class,'userCreate'])->name('user.leaves.create');  

                Route::post('leaves/{user_id}/store',[LeavesController::class,'userStore'])->name('user.leaves.store');  

                Route::get('quiz-delete/{quiz_id}',[QuizController::class,'delete'])->name('quiz.delete');  
                Route::get('quiz-send/{quiz_id}',[QuizController::class,'send'])->name('quiz.send');  

                Route::resource('quiz',QuizController::class,['except'=>['destroy','show']]);
                
                Route::get('logs',[LogController::class,'index'])->name('logs.index');  

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable 
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

  public $table = 'users';

    public $fillable = ['company_id','profile_pic','gender','fullname','position','birthdate','email','personal_email','contact','emergency_contact','address','info','role','activation_code','temp_photo','confirm_code','password','note','deactive_date','joining_date','resign_date','serving_date','is_verified','device_id','pay_code'];

    protected $hidden = ['remember_token','created_at','updated_at'];

    protected $dates = ['deleted_at'];

  public function getBirthdateAttribute($value)
  {
      return date("d-m-Y", strtotime($value));
  }
  public function setBirthdateAttribute($value)
  {
    $this->attributes['birthdate'] = date('Y-m-d',strtotime($value));
  }
  public function setDeactiveDateAttribute($value)
  {
    $this->attributes['deactive_date'] = date('Y-m-d',strtotime($value));
  }

  public function getJoiningDateAttribute($value)
  {
      return date("d-m-Y", strtotime($value));
  }
  public function setJoiningDateAttribute($value)
  {
    $this->attributes['joining_date'] = date('Y-m-d',strtotime($value));
  }
  public function getResignDateAttribute($value)
  {
      return (!empty($value)) ? date("d-m-Y", strtotime($value)) : ""; 
  }
  public function setResignDateAttribute($value)
  {
      if (!empty($value)) {
        $this->attributes['resign_date'] = date('Y-m-d',strtotime($value));
      }else{
        $this->attributes['resign_date'] = NULL;
      }
  }
  public function getServingDateAttribute($value)
  {
      return (!empty($value)) ? date("d-m-Y", strtotime($value)) : ""; 
  }
  public function setServingDateAttribute($value)
  {
      if (!empty($value)) {
        $this->attributes['serving_date'] = date('Y-m-d',strtotime($value));
      }else{
        $this->attributes['serving_date'] = NULL;
      }
  }

  // public function getProfilePicAttribute($value)
  // {
  //     return url("upload").'/'.$value;
  // }
  public function countPending() {
    return $this->hasMany('App\Models\Leave','user_id','id');
  }

  public function countApprove() {
    return $this->hasMany('App\Models\Leave','user_id','id');
  }

  public function countDisApprove() {
    return $this->hasMany('App\Models\Leave','user_id','id');
  }
  public function userPosition(){
      return $this->hasOne('App\Models\Position','id','position');
  }
}

resources/views/user/create.blade.php
@extends('layout.layout')
@section('content')
<div class="page-title">
    <div>
    <h1>Empolyee</h1>
        <ul class="breadcrumb side">
            <li><i class="fa fa-home fa-lg"></i></li>
            <li>Create Employee</li>
        </ul>
    </div>
</div>
<div class="clearix"></div>
<div class="row">
    <div class="col-md-3" style="padding: 0">
        <div class="card">
            <div class="card-body">
                <div class=" avtar text-center">

                    @if(\Session::has('image_name'))
                        <img src="/temp_image/<?=\trim(Session::get('image_name'))?>" alt="" style="width:150px;height:150px;margin-bottom: 20px">
                        <!-- <a href="http://timeloggerapp.thinktanker.in/user/profile/upload-photo" class="btn btn-primary iframe cboxElement">Change Photo</a>  -->
                        <a href="<?= URL::route('user.profile.upload.get') ?>" class="btn btn-primary iframe">Change Photo</a>  
                    @else
                        <img src="/images/user-icon.jpg" alt="" style="width:150px;height:150px;margin-bottom: 20px">
                        <!-- <a href="http://timeloggerapp.thinktanker.in/user/profile/upload-photo" class="btn btn-primary iframe cboxElement">Upload Photo</a> -->
                        <a href="<?= URL::route('user.profile.upload.get') ?>" class="btn btn-primary iframe">Add Photo</a>
                    @endif
                </div>
                <span class='text-danger' id="image_error"></span>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="card">
        <h3 class="card-title">Create</h3>
        <div class="card-body">
            <?= Form::open(array('class' => 'form-horizontal' ,'files' => true,'id'=>'usercreate')) ?>
            {{ session('msg') }}
     	<div class="form-group">
            <label class="control-label col-sm-3" for="inputGender">Gender</label>
            <div class="col-sm-9">
                <?= Form::radio('gender', 'male','true'); ?> Male
             	<?= Form::radio('gender', 'female'); ?> Female
            </div>
        </div>         
        <div class="form-group">
            <label class="control-label col-sm-3" for="inputFull Name">Full Name</label>
            <div class="col-sm-9">
                <?= Form::text('fullname',old('fullname'), ['class' => 'form-control', 'placeholder' => 'Full Name']); ?>
                <span class='text-danger' id="fullname_error"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="inputposition Name">Position</label>
            <div class="col-sm-9">
               <?= Form::select('position',$position,old('position') ,['class' => 'form-control select2','id'=>'position']); ?>
               <span class='text-danger' id="position_error"></span>
            </div>
        </div>
        <div class="form-group">
         	<label class="control-label col-sm-3" for="inputDate of Birth">Date of Birth</label>
            <div class="col-sm-9">
                <?= Form::text('birthdate',old('birthdate'), ['class' => 'form-control', 'id'=>'birth_Date','placeholder' => 'Date of Birth' , 'autocomplete'=>'off']); ?>
                <span class='text-danger' id="birthdate_error"></span>
            </div>
        </div> 
        <div class="form-group">
            <label class="control-label col-sm-3" for="inputEmail">Email</label>
            <div class="col-sm-9">
                <?= Form::email('email',old('email'), ['class' => 'form-control', 'placeholder' => 'Email']); ?>
                <span class='text-danger' id="email_error"></span>
            </div>
        </div>    
        <div class="form-group">
            <label class="control-label col-sm-3" for="inputPassword">Password</label>
            <div class="col-sm-9">
                <?= Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password']); ?>
                <span class='text-danger' id="password_error"></span>
            </div>
        </div>  
        <div class="form-group">
            <label class="control-label col-sm-3" for="inputConfirmPassword">Confirm Password</label>
            <div class="col-sm-9">
                <?= Form::password('password_confirmation', ['class' => 'form-control', 'placeholder' => 'Password']); ?>
                <span class='text-danger' id="password_confirmation_error"></span>
            </div>
        </div> 
        <div class="form-group">
            <label class="control-label col-sm-3" for="inputContact No">Contact No</label>
            <div class="col-sm-9">
                <?= Form::text('contact',old('contact'), ['class' => 'form-control', 'placeholder' => 'Contact No']); ?>
                <span class='text-danger' id="contact_error"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="inputEmergency No">Emergency Contact No</label>
            <div class="col-sm-9">
                <?= Form::text('emergency_contact',old('emergency_contact'), ['class' => 'form-control', 'placeholder' => 'Emergency Contact No']); ?>
                <span class='text-danger' id="emergency_contact_error"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="inputAddress">Address</label>
            <div class="col-sm-9">
                <?= Form::text('address',old('address'), ['class' => 'form-control', 'placeholder' => 'Address']); ?>
                <span class='text-danger' id="address_error"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="inputJoiningDate">Joining Date</label>
            <div class="col-sm-9">
                <?= Form::text('joining_date',old('joining_date'), ['class' => 'form-control', 'placeholder' => 'JoiningDate','id'=>'joining_date','autocomplete'=>'off']); ?>
                <span class='text-danger' id="joining_date_error"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="inputHobby">Hobby</label>
            <div class="col-sm-9">
                <?= Form::text('hobby',old('hobby'), ['class' => 'form-control', 'placeholder' => 'Hobby']); ?>
                <span class='text-danger' id="hobby_error"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="inputJoiningDate">Time Machine Code</label>
            <div class="col-sm-9">
                <?= Form::text('code',old('code'), ['class' => 'form-control', 'placeholder' => 'Time Machine Code','id'=>'code']); ?>
                <span class='text-danger' id="code_error"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-9 col-md-offset-3">
                <!-- <button type="button" class="btn btn-primary submit" id="submit" name="save_button" value="save_new">Save & New</button> -->
                <button type="button" class="btn btn-primary submit" id="submit1" name="save_button" value="save_exit">Save & Exit</button>
                <a href="<?=URL::route('user.index',['type'=>'currentemp'])?>">
                    <button type="button" class="btn btn-white btn-default" value="cancel" id="" name="cancel">Cancel</button>
                </a>
                {!! Form::close() !!}
            </div>
        </div>
        </div>
        </div>
    </div>
</div>    
@stop
@section('style')
<?= Html::style('asset/css/bootstrap-datepicker.css') ?> 
<?= Html::style('css/colorbox.css') ?>
@stop
@section('script')
<!-- <script src="https://code.jquery.com/jquery-1.10.2.js"></script> -->
<?= Html::script('asset/js/bootstrap-datepicker.min.js') ?>
<?= Html::script('js/jquery.colorbox-min.js') ?>
<!-- <script src="http://malsup.github.com/jquery.form.js"></script>  -->
<!-- <script src="http://malsup.github.io/jquery.form.js"></script>  -->
<?= Html::script('asset/js/malsup.github.io.js') ?>
<?= Html::script('asset/js/select2.min.js') ?>

<script type="text/javascript">
    jQuery(document).ready(function() {

        var birthdate = "{{ old('birthdate')}}";
        var currentDate = new Date();  
        $('#birth_Date').datepicker({
            format: "dd-mm-yyyy",
            autoclose: true,
            todayHighlight: true,
            endDate:currentDate,
        });

        var joining_date = "{{ old('joining_date')}}";
        var currentDate = new Date();  
        $('#joining_date').datepicker({
            format: "dd-mm-yyyy",
            autoclose: true,
            todayHighlight: true,
            endDate:currentDate,
        });

        if('<?= Session::has('image_name')?>'){
            arr = [''];
        }else{
            arr = ['Image field is required'];
        }
        $('.submit').click(function(){
            button_id = $(this).attr('id');
            token = '<?= csrf_token()?>';
            $('#usercreate').ajaxSubmit({
                url: "<?=route('user.store')?>",
                type: 'POST',
                data: { "_token" : token,'id':button_id},
                dataType: 'json',
                beforeSubmit:function(){
                    $('.pace-inactive').css('display','block');
                },
                success : function(resp){
                    if(resp == "new"){
                        window.setTimeout(function(){window.location.href = '<?=URL::route('user.create',['type'=>'currentemp'])?>';},3000)
                    }else{
                        window.location.href = '<?=URL::route('user.index',['type'=>'currentemp'])?>';
                    }
                    $('.pace-inactive').css('display','none');

                    iziToast.success({
                        title:'Ok',
                        message: "User created Successfully",
                    });
                },
                error : function(respObj){
                    iziToast.error({
                        title:'Ok',
                        message: "There were some error!",
                    });
                    $("[id$='_error']").empty();
                    respObj.responseJSON['image'] = arr;
                    $.each(respObj.responseJSON, function(k,v){
                        $('#'+k+'_error').text(v);
                    });
                    $('.pace-inactive').css('display','none');
                }

            });
        });
        parent.$.fn.colorbox.close();
        $(".iframe").colorbox({
            iframe   : true,
            width    : "70%",
            height   : "80%",
            onClosed : function(){ parent.location.reload(true); }
        });
    });

    //position
    $('#position').prepend('<option value="">Select Positions</option>');
    $("#position").val($(".select2 option:first").val());
    $("#position")
    .select2({
        placeholder: 'Select type',
        width: '100%',
        minimumResultsForSearch: Infinity
      })
    .on('select2:close', function() {
        var el = $(this);
        if(el.val()==="NEW") {
          var newval = prompt("Enter New Positions: ");
          if(newval !== null) {
            $.ajax({
                url     : "{{URL::route('position.store')}}",
                type    : 'post',
                dataType: 'html',
                data    :{
                            'newval': newval,
                            '_token':'{{csrf_token()}}'
                        },
                success    : function(resp) 
                {
                    el.append('<option value='+resp+'>'+newval+'</option>')
                      .val(newval);
                }
            });
          }
        }
    });

</script>
<?= Html::script('asset/js/form.demo.min.js') ?>
@include('partials.alert')
@stop

resources/views/user/recycle.blade.php
@extends('layout.layout')
@section('content')
<div class="page-title">
   <div>
      <h1>Employees</h1>
      <ul class="breadcrumb side">
        <li><i class="fa fa-home fa-lg"></i></li>
        <li class="active"><a href="<?= URL::route('user.index') ?>">Employees Table</a></li>
        <li class="active"><a href="<?=URL::route('user.recyclebin')?>">Inactive Employees</a></li>
      </ul>
   </div>
   <div><a href="<?=URL::route('user.create')?>" class="btn btn-primary btn-flat"><i class="fa fa-lg fa-plus"></i></a><a href="#" class="btn btn-info btn-flat"><i class="fa fa-lg fa-refresh"></i></a><a href="#" class="btn btn-warning btn-flat"><i class="fa fa-lg fa-trash"></i></a></div>
</div>
<div class="flash-message">
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
      @if(Session::has('alert-' . $msg))

      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
      @endif
    @endforeach
</div>
<div class="row">
   <div class="col-md-12">
      <div class="card">
         <div class="card-body">
            <table id="employee" class="table table-hover table-bordered" border="1 px">
               <thead>
                  <tr>
                     <th><input type="checkbox" id="selectall1" name="selectall"></th>
                     <th>Profile_pic</th>
                     <th>Fullname</th>
                     <th>Position</th>
                     <th>Email</th>
                     <th>Action</th>
                  </tr>
               </thead>
               <tbody></tbody>
            </table>
         </div>
      </div>
   </div>
</div>
@stop
@section('script')
<?= Html::script('asset/DataTables/media/js/jquery.dataTables.js') ?>
<?= Html::script('asset/DataTables/media/js/dataTables.bootstrap.min.js') ?>
<?= Html::script('asset/js/plugins/sweetalert.min.js') ?>
<?= Html::script('asset/js/plugins/select2.min.js') ?>
<script>
   $(document).ready(function()
   {
     $('#employee').DataTable(
     {
       "bProcessing" : true,
       "bServerSide" : true,
       "ajax" :"<?= URL::route('user.recyclebin') ?>",
       "aaSorting": [
                    [ 2, "asc" ]
        ],
       "aoColumns"   :[
                   {
                     mData: 'id' ,
                     bSortable : false,
                     mRender   : function (v, t, o) {
                     return   '<div class="checkboxer checkboxer-indigo form-inline">' +
                                       '<input type="checkbox" id="chk_'+v+'" name="id[]" value="'+v+'">' +
                                       '<label for="chk_'+v+'"></label>' +
                               '</div>';
                     }
                   },
                   { mData: 'profile_pic',
                     bSortable : false,
                     mRender: function(v,t,o)
                     {
                         var path = "<?= asset('upload/"+v+"'); ?>";
                         var img = "<img height='100' width='100' src='"+path+"''>";
                         return img; 
                     }
                   },
                   { mData: 'fullname'
                     //bSortable: true,
                   },
                   { mData: 'position'
                     //bSortable: true,
                   },
                   
                   { mData: 'email',
                     bSortable: false,
                   },
                  
                   { mData: null,
                     bSortable : false,
                     mRender:function(v,t,o)
                     {
                       var path     = "<?= URL::route('user.restore',array('id'=>':id')) ?>";
                       var path_del = "<?= URL::route('user.destroy',array('id'=>':id')) ?>";
                         
                       path     = path.replace(':id',o['id']);
                       path_del = path_del.replace(':id',o['id']);
                       
                        
                       var extra_html = '<a href="'+path+'" class="fa fa-undo"></a> |' +
                       
                                       '<a href="'+path_del+'" class="fa fa-fw fa-trash-o"></a>' 
                                         
                                          
   
                         return extra_html;
                       }
                     },
               ],
   });
      //   $('#demoNotify').click(function(){
      //   $.notify({
      //     title: "Update Complete : ",
      //     message: "Something cool is just updated!",
      //     icon: 'fa fa-check-circle' 
      //   },{
      //     type: "danger"
      //   });
      // });
           $('#employee input:checkbox[name="selectall"]').click(function() 
           {
               var is_checked = $(this).is(':checked');
               $(this).closest('table').find('tbody tr td:first-child input[type=checkbox], thead tr th:first-child input[type=checkbox], tfoot tr th:first-child input[type=checkbox]')
                                       .prop('checked', is_checked);
           });
   });
</script>
@stop

resources/views/user/upload-photo.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Upload Profile Photo</title>
	<?= Html::style('front/css/style.css') ?>
	<?= Html::style('plugins/krajee/css/fileinput.min.css') ?>
	<?= Html::script('front/js/jquery.min.js') ?>
	<?= Html::script('plugins/krajee/js/fileinput.min.js') ?>
	<style>
		.form-control {border-radius: 0; background: none; border:1px solid #EEE;  outline: none; -webkit-box-shadow: none !important; -moz-box-shadow: none !important; box-shadow: none !important; height:32px;}
		/*.btn-file {height:40px; background:#000 !important; padding:10px;}*/
		.btn-file:hover {height:32px; background:#CCC !important; color:#000; }
		/*button[class^="fileinput-"], button[class*=" fileinput-"]{ padding: 10px !important }*/
	</style>
	
<script type="text/javascript">
	$(document).ready(function(){
		$("#profile_pic").fileinput({ 
			showPreview: false,
            allowedFileExtensions: ["jpg", "gif", "png", "jpeg"],
            // previewFileType: "image",
            showUpload : true,
            uploadClass: 'btn btn-primary',
			uploadTitle: 'Please upload file'
		});
	});
</script>
</head>
<body>
	<div class="text-center" align="center">

		<?= Form::open(array('route' => array('user.profile.upload.post'), 'id' => 'frm_profile_photo', 'class' => 'pt60 pb60', 'method' => 'POST', 'files' => true)) ?>
			<input type="hidden" name="_token" value="{!! csrf_token() !!}">
			<input type="hidden" name="id" value="<?= $id?>">
			<b>only jpg, and png images are allowed</b><br/>
			<b>image size should be less than 4 mb</b>
			
			<div class="col-md-2">
				<?= Form::file('profile_pic', array('class' => 'file', 'id' => 'profile_pic')) ?><br/>
			</div>
			<span class="text-danger">{{ $errors->first('profile_pic') }}</span>
		
		<?= Form::close() ?>
	</div>

</body>
</html>