routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Auth\PasswordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AssetsController;
use App\Http\Controllers\AllowUserLogsController;
use App\Http\Controllers\AssetsMasterController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\HolidaysController;
use App\Http\Controllers\HolidaysMasterController;
use App\Http\Controllers\HolidaysYearController;
use App\Http\Controllers\AptitudeController;
use App\Http\Controllers\LeavesController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\ServicesController;
use App\Http\Controllers\ShowController;
use App\Http\Controllers\TimeloggerController;
use App\Http\Controllers\UserPermissionController;
use App\Http\Controllers\userPermissionMaster;
use App\Http\Controllers\WeeklyLogsController;
use App\Http\Controllers\WorkingDaysController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/dashboard',[TimeloggerController::class,'admin'])->middleware(['auth'])->name('dashboard.admin');
Route::get('/logout',[AuthenticatedSessionController::class,'destroy'])->name('Logout');

Route::group(['middleware' => 'web'], function() {


    Route::post('/trash',[TimeloggerController::class, 'trash'])->name('user.trash');
    Route::get('/recyclebin',[TimeloggerController::class, 'recyclebin'])->name('user.recyclebin');

    Route::get('/restore/{id}',[TimeloggerController::class, 'restore'])->name('user.restore');

    Route::get('/user/delete/{id}',[TimeloggerController::class, 'destroy'])->name('user.destroy');

    Route::get('denied',function(){
            return 'denied';
        })->name('user.denied');
     

    /*User authinticate*/
    Route::group(array('middleware' => ['auth']), function(){

            // Route::get('dashboard',[TimeloggerController::class,'admin'])->name('dashboard.admin');

            Route::post('get-selected-pemission',[UserPermissionController::class,'getSelectedPermissions'])->name('selectpermission.get');
           
           
        //karishma  
            Route::post('leaves/delete',[LeavesController::class,'destroy'])->name('leaves.delete');
            Route::post('leave/status',[LeavesController::class,'leaveStatus'])->name('leave.status');

            Route::post('notification/isread',[LeavesController::class,'notificationIsread'])->name('notification.isread');

            Route::post('notification/isview',[LeavesController::class,'notificationIsview'])->name('notification.isview');

            Route::post('leave/checkbox_status',[LeavesController::class,'checkboxtatus'])->name('leave.checkboxtatus');

            Route::get('logs/exportlogs/{id}/{month}/{year}',[ShowController::class,'exportlogs'])->name('logs.exportlogs');

            Route::get('logs/alluserexportlogs/{id}/{month}/{year}',[ShowController::class,'allUserExportLogs'])->name('logs.alluserexportlogs');

            Route::get('workingdays',[WorkingDaysController::class,'index'])->name('admin.workingdays');

            // Route::post('workingdays',[WorkingDaysController::class,'workingdays'])->name('admin.workingdays');

            Route::post('store/workingdays',[WorkingDaysController::class,'storeworkingdays'])->name('admin.store.workingdays');

            Route::get('user/profile/upload-photo/{id?}',[TimeloggerController::class,'getUploadProfilePhoto'])->name('user.profile.upload.get');

            Route::post('user/profile/upload-photo',[TimeloggerController::class,'postUploadProfilePhoto'])->name('user.profile.upload.post');

            Route::get('/user/profile/crop-photo',[TimeloggerController::class,'getCropProfilePhoto'])->name('user.profile.photo.crop.get');

            Route::post('/user/profile/crop-photo',[TimeloggerController::class,'postCropProfilePhoto'])->name('user.profile.photo.crop.post');

            Route::post('/user/deactive',[TimeloggerController::class,'userDeactive'])->name('user.deactive');

            Route::post('position/store',[TimeloggerController::class,'positionStore'])->name('position.store');

            Route::post('/leaves/chart',[TimeloggerController::class,'getChart'])->name('dashboard.leaves.chart');

            Route::post('/leaves/secondchart',[TimeloggerController::class,'getSecondChart'])->name('dashboard.leaves.secondchart');

            Route::post('/leaves/logs-chart',[TimeloggerController::class,'getLogsChart'])->name('dashboard.logs.chart');

            Route::post('workingdays/hours',[TimeloggerController::class,'workingdaysHours'])->name('admin.workingdays.hours');


            Route::resource('services',ServicesController::class,['except'=>['delete','show']]);
        
            Route::post('services/delete',[ServicesController::class,'delete'])->name('services.delete');
            Route::post('category/store',[ServicesController::class,'categoryStore'])->name('category.store');
            Route::get('weeklylogs',[WeeklyLogsController::class,'weeklyLogs'])->name('admin.weeklylogs');
            //end karishma
            //rushik
            Route::resource('/holiday-master',HolidaysMasterController::class,['except'=>['delete','show']]);
             
            Route::post('/holiday-master/delete',[HolidaysMasterController::class,'delete'])->name('holiday-master.delete');

            Route::resource('/holiday-year',HolidaysYearController::class,['except'=>['delete','show']]);
        
            Route::post('/holiday-year/delete',[HolidaysYearController::class,'delete'])->name('holiday-year.delete');

            Route::get('holiday/upload-photo',[HolidaysMasterController::class,'getUploadProfilePhoto'])->name('holiday.upload.get');

            Route::post('holiday/upload-photo',[HolidaysMasterController::class,'postUploadProfilePhoto'])->name('holiday.upload.post');
        
            Route::get('/holiday/crop-photo',[HolidaysMasterController::class,'getCropProfilePhoto'])->name('holiday.photo.crop.get');
       
            Route::post('/holiday/crop-photo',[HolidaysMasterController::class,'postCropProfilePhoto'])->name('holiday.photo.crop.post');

            Route::post('/dashboard/leaves/store',[LeavesController::class,'leavestore'])->name('dashboard.leaves.store');

            Route::post('/dashboard/leaves/second/store',[LeavesController::class,'leavesecondstore'])->name('dashboard.leaves.second.store');

            Route::post('/dashboard/leaves/third/store',[LeavesController::class,'leavethirdstore'])->name('dashboard.leaves.third.store');

            Route::post('/user/checkin',[TimeloggerController::class,'checkIn'])->name('user.checkin');

            Route::resource('assets',AssetsController::class,['except'=>['delete','show']]);

            Route::post('assets/delete',[AssetsController::class,'delete'])->name('assets.delete');

            Route::resource('assets/master',AssetsMasterController::class,['except'=>['delete','show']]);

            Route::get('assets/master/create',[AssetsMasterController::class,'create'])->name('assets.master.create');

            Route::get('assets/master/index',[AssetsMasterController::class,'index'])->name('assets.master.index');

            Route::post('assets/master/store',[AssetsMasterController::class,'store'])->name('assets.master.store');

            Route::get('assets/master/edit/{id}',[AssetsMasterController::class,'edit'])->name('assets.master.edit');

            Route::post('assets/master/delete',[AssetsMasterController::class,'delete'])->name('assets.master.delete'); 

            Route::post('assets/master/update',[AssetsMasterController::class,'update'])->name('assets.master.update');  
 

            Route::post('getDevice',[AssetsController::class,'getDevice'])->name('getDevice.index');  
            //end rushik

            Route::post('getlogs',[LogController::class,'getLogs'])->name('getlogs.index');  

            Route::post('logs/import/daily',[LogController::class,'importlogs'])->name('logs.logsimport');  
            Route::get('user/leaves/export/{user}/{type}/{year}',[LeavesController::class,'exportLeaves'])->name('leaves.export');  



        Route::group(array('middleware'=> ['acl']),function(){

                Route::resource('/user',TimeloggerController::class,['except'=>['destroy']]);
                Route::resource('/holiday',HolidaysController::class,['except'=>['destroy']]);
                Route::resource('/leaves',LeavesController::class,['except'=>['destroy','show']]);
                Route::resource('/allowuserlogs',AllowUserLogsController::class,['except'=>['destroy','show']]);


                Route::get('holiday/delete/{id}',[HolidaysController::class,'destroy'])->name('holidays.delete');  

                Route::get('leaves/{user_id}/create',[LeavesController::class,'userCreate'])->name('user.leaves.create');  

                Route::post('leaves/{user_id}/store',[LeavesController::class,'userStore'])->name('user.leaves.store');  

                Route::get('quiz-delete/{quiz_id}',[QuizController::class,'delete'])->name('quiz.delete');  
                Route::get('quiz-send/{quiz_id}',[QuizController::class,'send'])->name('quiz.send');  

                Route::resource('quiz',QuizController::class,['except'=>['destroy','show']]);
                
                Route::get('logs',[LogController::class,'index'])->name('logs.index');  

app/Models/Quiz.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Quiz extends Model
{

	public $table = 'quizzes';

	public $fillable = ['question','time'];

	public function getCreatedAtAttribute($value)
	{
		return date('d-M h:i A',strtotime($value));
	}

	public function getImageAttribute($value)
	{
		if ($value != NULL AND $value != '') {
			return asset('upload/quiz/').'/'.$value;
		}
		return NULL;
	}

}

resources/views/quiz/create.blade.php
@extends('layout.layout')
@section('content')
<div class="page-title">
    <div>
    <h1>Quiz</h1>
        <ul class="breadcrumb side">
            <li><i class="fa fa-home fa-lg"></i></li>
            <li>Create</li>
        </ul>
    </div>
</div>
<div class="clearix"></div>
<div class="col-md-12">
    @include('partials.alert')
    <div class="card">
        <h3 class="card-title">Create</h3>
        <div class="card-body">
            <?= Form::open(array('url' => route('quiz.store') ,'class' => 'form-horizontal','files' => true)) ?>
                <div class="form-group">
                    <label class="control-label col-sm-2">Question</label>
                    <div class="col-sm-8">
                        <?= Form::text('question', old('question'), ['class' => 'form-control', 'placeholder' => 'Quiz Question']); ?>
                      	<?= $errors->first('question',"<span class='text-danger'>:message</span>");?>
                    </div>
             	</div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Quiz Image</label>
                    <div class="col-sm-8">
                        <?= Form::file('image',['class' => 'form-control']) ?>
                        <?= $errors->first('image','<span class="help-inline text-danger">:message</span>') ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2">Time of Question</label>
                    <div class="col-sm-8">
                        <?= Form::number('time', old('time'), ['class' => 'form-control', 'placeholder' => 'Time In Seconds Per Question']); ?>
                      	<?= $errors->first('time',"<span class='text-danger'>:message</span>");?>
                    </div>
             	</div>
                <div class="form-group">
                    <label class="control-label col-sm-2">Select All Users</label>
                    <div class="col-sm-8">
                        <input type="checkbox" id="selectall" >
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2">Select Users</label>
                    <div class="col-sm-8">
                        <?= Form::select('user[]',$users,old('user'),['class' => 'form-control','multiple' => true,'id' => 'user_ask']); ?>
                        <?= $errors->first('user',"<span class='text-danger'>:message</span>");?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Options</label>
                    <div class="col-sm-8" style="border:1px solid #DDD;padding:20px;left: 14px;">
                        <div class="form-inline" id="dynamic_form">
                            <input type="radio" name="is_true" value="1" id="is_true" />&nbsp&nbsp
                            <input type="text" style="margin-bottom:10px;width:52.5%;" class="form-control" name="options" id="options" placeholder="enter options">
                            <a href="javascript:void(0)" style="vertical-align:3px;margin-left:5px;" class="btn btn-primary" id="plus5">Add More</a>
                            <a href="javascript:void(0)" style="vertical-align:3px;margin-left:5px;" class="btn btn-danger" id="minus5">Remove</a>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-8 col-md-offset-3">
                        <button name="quiz_post" value="exit" type="submit" class="btn btn-primary">Save & Exit</button>
                        <button name="quiz_post" value="send" type="submit" class="btn btn-primary">Save & Send</button>
                        <a href="<?= route('quiz.index') ?>" class="btn btn-danger">Cancel</a>
                    </div>
                </div>
       	    <?= Form::close(); ?>
        </div>
    </div>
</div>
@stop
@section('script')
<?= Html::script('asset/js/jquery.js') ?>
<?= Html::script('js/jquery-dynamic-form.js') ?>
<?= Html::script('front/js/select2.min.js') ?>
<script type="text/javascript">

$(document).ready(function() {

    $("#user_ask").select2();

    $("#selectall").click(function(){
        if($("#selectall").is(':checked') ){
            $("#user_ask > option").prop("selected","selected");
            $("#user_ask").trigger("change");
        }else{
            $("#user_ask > option").removeAttr("selected");
             $("#user_ask").trigger("change");
         }
    });

    $('input[type="radio"]').click(function(){
        $('input[type="radio"]').not($(this)).prop('checked',false);
    });

    var dynamic_form =  $("#dynamic_form").dynamicForm("#plus5", "#minus5", {
        limit:100,
        normalizeFullForm : false,
    });

    @if(!count($errors))
        dynamic_form.inject([{"options":""},{"options":""}]);
    @endif

    @if(count($errors) >= 0)
        dynamic_form.inject( <?= json_encode(old('dynamic_form.dynamic_form')) ?> );

        var detail_Errors = <?= json_encode($errors->toArray()) ?>;

        $.each(detail_Errors, function(id, msg){
            var id_arr = id.split('.');
            $('#options' + id_arr[id_arr.length-2]).parent().append('</br><span class="help-inline text-danger">'+ msg[0] +'</span></br>');
        });
    @endif

});
</script>
@stop

resources/views/quiz/edit.blade.php
@extends('layout.layout')
@section('content')
<div class="page-title">
    <div>
    <h1>Quiz</h1>
        <ul class="breadcrumb side">
            <li><i class="fa fa-home fa-lg"></i></li>
            <li>Edit</li>
        </ul>
    </div>
</div>
<div class="clearix"></div>
<div class="col-md-12">
    @include('partials.alert')
    <div class="card">
        <h3 class="card-title">Edit</h3>
        <div class="card-body">
            <?= Form::model($quiz_edit,array('route' => ['quiz.update',$quiz_edit->id],'class' => 'form-horizontal','method' => 'put','files' => true)) ?>
                <div class="form-group">
                    <label class="control-label col-sm-2">Question</label>
                    <div class="col-sm-8">
                        <?= Form::text('question', old('question'), ['class' => 'form-control', 'placeholder' => 'Quiz Question']); ?>
                      	<?= $errors->first('question',"<span class='text-danger'>:message</span>");?>
                    </div>
             	</div>
                @if($quiz_edit['image'] != NULL)
                <div class="form-group">
                    <label class="control-label col-sm-2">Question</label>
                    <div class="col-sm-8">
                        <img src="{{ $quiz_edit['image'] }}" height="150" width="150">
                    </div>
                </div>
                @endif
                <div class="form-group">
                    <label class="col-sm-2 control-label">Quiz Image</label>
                    <div class="col-sm-8">
                        <?= Form::file('image',['class' => 'form-control']) ?>
                        <?= $errors->first('image','<span class="help-inline text-danger">:message</span>') ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2">Time of Question</label>
                    <div class="col-sm-8">
                        <?= Form::number('time', old('time'), ['class' => 'form-control', 'placeholder' => 'Time In Seconds Per Question']); ?>
                      	<?= $errors->first('time',"<span class='text-danger'>:message</span>");?>
                    </div>
             	</div>
                <div class="form-group">
                    <label class="control-label col-sm-2">Select Users</label>
                    <div class="col-sm-8">
                        <?= Form::select('user[]',$users,old('user',$getSelectedUsers),['class' => 'form-control','multiple' => true,'id' => 'user_ask','style' => 'width:100%;']) ?>
                      	<?= $errors->first('user',"<span class='text-danger'>:message</span>");?>
                    </div>
             	</div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Options</label>
                    <div class="col-sm-8" style="border:1px solid #DDD;padding:20px;left: 14px;">
                        <div class="form-inline" id="dynamic_form">
                            <input type="text" style="margin-bottom:10px;width:52.5%;" class="form-control" name="options" id="options" placeholder="enter options">
                            <input type="radio" name="is_true" value="1" id="is_true" />
                            <a href="javascript:void(0)" style="vertical-align:3px;margin-left:5px;" class="btn btn-primary" id="plus5">Add More</a>
                            <a href="javascript:void(0)" style="vertical-align:3px;margin-left:5px;" class="btn btn-danger" id="minus5">Remove</a>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-8 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="<?= route('quiz.index') ?>" class="btn btn-danger">Cancel</a>
                    </div>
                </div>
       	    <?= Form::close(); ?>
        </div>
    </div>
</div>
@stop
@section('script')
<?= Html::script('asset/js/jquery.js') ?>
<?= Html::script('js/jquery-dynamic-form.js') ?>
<?= Html::script('front/js/select2.min.js') ?>

<script type="text/javascript">
jQuery(document).ready(function() {

    $('form').submit(function(){
        $(this).find('button:submit').html('<i class="fa fa-spinner fa-spin"></i>').prop('disabled', true);
    });

    $("#user_ask").select2();

    $('input[type="radio"]').click(function(){
        $('input[type="radio"]').not($(this)).prop('checked',false);
    });

    var dynamic_form =  $("#dynamic_form").dynamicForm("#plus5", "#minus5", {
        limit:100,
        normalizeFullForm : false,
    });

    dynamic_form.inject( <?= json_encode($final) ?> );

    @if($errors)

        var detail_Errors = <?= json_encode($errors->toArray()) ?>;

        $.each(detail_Errors, function(id, msg){
            var id_arr = id.split('.');
            $('#options' + id_arr[id_arr.length-2]).parent().append('<span class="help-inline text-danger">'+ msg[0] +'</span>');
        });
    @endif

});
</script>
@stop

resources/views/quiz/index.blade.php
@extends('layout.layout')
@section('content')
<div class="page-title">
    <div>
    <h1>Quiz</h1>
    <ul class="breadcrumb side">
        <li><i class="fa fa-home fa-lg"></i></li>
        <li>Questions List</li>
    </ul>
    </div>
    <div>
        <a href="<?=URL::route('quiz.create')?>" class="btn btn-primary btn-flat"><i class="fa fa-lg fa-plus"></i></a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
           <div class="card-body">
              <table id="employee" class="table table-hover table-bordered" border="1 px">
                 <thead>
                    <tr>
                        <th></th>
                        <th>Question</th>
                        <th>Time</th>
                        <th>Action</th>
                    </tr>
                 </thead>
                 <tbody></tbody>
              </table>
           </div>
        </div>
    </div>
</div>
@stop
@section('script')
<?= Html::script('asset/DataTables/media/js/jquery.dataTables.js') ?>
<?= Html::script('asset/DataTables/media/js/dataTables.bootstrap.min.js') ?>

<script>
    $(document).ready(function()
    {
        $('#employee').DataTable(
        {
            "bProcessing" : true,
            "bServerSide" : true,
            "ajax" :"<?= URL::route('quiz.index') ?>",
            "aaSorting": false,
            "aoColumns" :[{
                mData: "id",
                bSortable: false,
                bVisible: false
            },
            { mData: 'question',bSortable: false},
            { mData: 'time' ,bSortable: false},
            {
                mData: null,
                bSortable : false,
                mRender:function(v,t,o)
                {
                    var extra_html = '';

                    var path_del = "<?= route('quiz.delete',['id'=>':id']) ?>";
                    path_del = path_del.replace(':id',o['id']);

                    var path_edit = "<?= route('quiz.edit',['id'=>':id']) ?>";
                    path_edit = path_edit.replace(':id',o['id']);

                    var path_send = "<?= route('quiz.send',['id'=>':id']) ?>";
                    path_send = path_send.replace(':id',o['id']);

                    if(o['is_send'] == 0) {

                        extra_html += '<a href="'+path_edit+'" title="edit" class="fa fa-fw fa-edit"></a> | ';
                        extra_html += '<a href="'+path_del+'" title="delete" class="fa fa-fw fa-trash-o"></a> | ';
                        extra_html += '<a href="'+path_send+'" title="send" class="fa fa-fw fa fa-paper-plane"></a>';

                    } else {

                        extra_html += '<a href="'+path_del+'" class="fa fa-fw fa-trash-o"></a>';
                    }
                    return extra_html;
                }
            },
            ],
        });

    });
</script>
@stop